name: Deploy to GitHub Pages and Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout contact form backend
        uses: actions/checkout@v3
        with:
          repository: tokyoundergroundbeatzmassive/contact_form_backend
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: SAM Build and Deploy
        run: |
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name tubm-contact-form \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
            "ParameterKey=ApiId,ParameterValue=${CONTACT_FORM_API_GATEWAY_ID} \
             ParameterKey=SenderEmail,ParameterValue=${CONTACT_FORM_EMAIL} \
             ParameterKey=ReceiverEmail,ParameterValue=${CONTACT_FORM_EMAIL} \
             ParameterKey=AppPassword,ParameterValue=${APP_PASSWORD} \
             ParameterKey=RepositoryName,ParameterValue=${GITHUB_REPOSITORY#*/}"
        env:
          CONTACT_FORM_EMAIL: ${{ secrets.CONTACT_FORM_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}